### ISSUE TITLE
jquery-ui-lightness error after running application template

### ISSUE THREAD

**Issue by hortongn** [samvera-deprecated/curate#226]
Following the README, after using the application template and starting the server, the following error is displayed in the web browser: 

couldn't find file 'jquery-ui-lightness' (in /home/glen/.rvm/gems/ruby-1.9.3-p448/gems/curate-0.5.0/app/assets/stylesheets/curate.css.scss:11)

This and subsequent errors appear to be due to empty vendor/assets/stylesheets and vendor/assets/javascript directories.  Copying the needed files from the remote repo to those directories fixes the problem.

**Comment by jcoyne** [comment]
I'm not seeing that issue.  The file is in the vendor directory: https://github.com/ndlib/curate/blob/master/vendor/assets/stylesheets/jquery-ui-lightness.css

**Comment by jcoyne** [comment]
Hmm, when I generate from the template as you have done, I also get that issue:

```
Sprockets::FileNotFound in CatalogController#index
couldn't find file 'jquery-ui-lightness' (in /Users/justin/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/curate-0.5.0/app/assets/stylesheets/curate.css.scss:11)

Rails.root: /Users/justin/workspace/my_curate_application

Application Trace | Framework Trace | Full Trace
sprockets (2.10.0) lib/sprockets/context.rb:106:in `resolve'
sprockets (2.10.0) lib/sprockets/context.rb:146:in `require_asset'
sprockets (2.10.0) lib/sprockets/directive_processor.rb:217:in `process_require_directive'
sprockets (2.10.0) lib/sprockets/directive_processor.rb:167:in `block in process_directives'
sprockets (2.10.0) lib/sprockets/directive_processor.rb:165:in `each'
sprockets (2.10.0) lib/sprockets/directive_processor.rb:165:in `process_directives'
sprockets (2.10.0) lib/sprockets/directive_processor.rb:99:in `evaluate'
tilt (1.4.1) lib/tilt/template.rb:103:in `render'
sprockets (2.10.0) lib/sprockets/context.rb:197:in `block in evaluate'
sprockets (2.10.0) lib/sprockets/context.rb:194:in `each'
sprockets (2.10.0) lib/sprockets/context.rb:194:in `evaluate'
sprockets (2.10.0) lib/sprockets/processed_asset.rb:12:in `initialize'
sprockets (2.10.0) lib/sprockets/base.rb:374:in `new'
sprockets (2.10.0) lib/sprockets/base.rb:374:in `block in build_asset'
sprockets (2.10.0) lib/sprockets/base.rb:395:in `circular_call_protection'
sprockets (2.10.0) lib/sprockets/base.rb:373:in `build_asset'
sprockets (2.10.0) lib/sprockets/index.rb:94:in `block in build_asset'
sprockets (2.10.0) lib/sprockets/caching.rb:58:in `cache_asset'
sprockets (2.10.0) lib/sprockets/index.rb:93:in `build_asset'
sprockets (2.10.0) lib/sprockets/base.rb:287:in `find_asset'
sprockets (2.10.0) lib/sprockets/index.rb:61:in `find_asset'
sprockets (2.10.0) lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
sprockets (2.10.0) lib/sprockets/processed_asset.rb:105:in `each'
sprockets (2.10.0) lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
sprockets (2.10.0) lib/sprockets/processed_asset.rb:97:in `build_required_assets'
sprockets (2.10.0) lib/sprockets/processed_asset.rb:16:in `initialize'
sprockets (2.10.0) lib/sprockets/base.rb:374:in `new'
sprockets (2.10.0) lib/sprockets/base.rb:374:in `block in build_asset'
sprockets (2.10.0) lib/sprockets/base.rb:395:in `circular_call_protection'
sprockets (2.10.0) lib/sprockets/base.rb:373:in `build_asset'
sprockets (2.10.0) lib/sprockets/index.rb:94:in `block in build_asset'
sprockets (2.10.0) lib/sprockets/caching.rb:58:in `cache_asset'
sprockets (2.10.0) lib/sprockets/index.rb:93:in `build_asset'
sprockets (2.10.0) lib/sprockets/base.rb:287:in `find_asset'
sprockets (2.10.0) lib/sprockets/index.rb:61:in `find_asset'
sprockets (2.10.0) lib/sprockets/bundled_asset.rb:16:in `initialize'
sprockets (2.10.0) lib/sprockets/base.rb:377:in `new'
sprockets (2.10.0) lib/sprockets/base.rb:377:in `build_asset'
sprockets (2.10.0) lib/sprockets/index.rb:94:in `block in build_asset'
sprockets (2.10.0) lib/sprockets/caching.rb:58:in `cache_asset'
sprockets (2.10.0) lib/sprockets/index.rb:93:in `build_asset'
sprockets (2.10.0) lib/sprockets/base.rb:287:in `find_asset'
sprockets (2.10.0) lib/sprockets/index.rb:61:in `find_asset'
sprockets (2.10.0) lib/sprockets/environment.rb:75:in `find_asset'
sprockets (2.10.0) lib/sprockets/base.rb:295:in `[]'
sprockets-rails (2.0.1) lib/sprockets/rails/helper.rb:144:in `lookup_asset_for_path'
sprockets-rails (2.0.1) lib/sprockets/rails/helper.rb:113:in `block in stylesheet_link_tag'
sprockets-rails (2.0.1) lib/sprockets/rails/helper.rb:112:in `map'
sprockets-rails (2.0.1) lib/sprockets/rails/helper.rb:112:in `stylesheet_link_tag'
curate (0.5.0) app/views/layouts/boilerplate.html.erb:13:in 
```

**Comment by jcoyne** [comment]
When I attempt to precompile assets I get a slightly different error:

```
RAILS_ENV=production rake assets:precompile
...
rake aborted!
couldn't find file 'jquery-ui-1.9.2/jquery.ui.widget'
  (in /Users/justin/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/curate-0.5.0/app/assets/javascripts/curate.js:11)

```

**Comment by jcoyne** [comment]
Looks like vendor is not a listed path in the gemspec.
