### ISSUE TITLE
Error when config/manager_usernames.yml is missing

### ISSUE THREAD

**Issue by jcoyne** [samvera-deprecated/curate#424]
It should provide something helpful like "ERROR: missing config file: config/manager_usernames.yml", instead it says:

```
ERROR -- : Curate caught a registered error: NoMethodError
    undefined method `[]' for false:FalseClass
    Backtrace:
    /opt/curate_dce/shared/bundle/ruby/2.0.0/gems/curate-0.6.5/app/models/curate/user_behavior/base.rb:36:in `manager_usernames'
    /opt/curate_dce/shared/bundle/ruby/2.0.0/gems/curate-0.6.5/app/models/curate/user_behavior/base.rb:32:in `manager?'
    /opt/curate_dce/shared/bundle/ruby/2.0.0/gems/curate-0.6.5/app/models/concerns/curate/ability.rb:10:in `curate_permissions'
    /opt/curate_dce/shared/bundle/ruby/2.0.0/gems/hydra-access-controls-6.4.1/lib/hydra/ability.rb:52:in `block in hydra_default_permissions'
```

**Comment by hortongn** [comment]
This was just fixed as part of pull request #444 

https://github.com/projecthydra/curate/commit/71935799b9b058931ae2c0770f03056ba80d8f78#diff-0ab4af97ccc7ffdf2bf68251ec452e0dR31
