### ISSUE TITLE
Clean run of generator results in ActiveFedora::UnregisteredPredicateError when you try to upload

### ISSUE THREAD

**Issue by flyingzumwalt** [samvera-deprecated/curate#492]
With curate 0.6.6 or using the current master branch of projecthydra/curate, After running the `rails generate curate` generator and running `rake db migrate`, I get _ActiveFedora::UnregisteredPredicateError in CurationConcern::ArticlesController#new_
 when I visit http://localhost:3000/concern/articles/new.  Same applies for /concern/datasets/new, etc.

Excerpt from the backtrace:

```
active-fedora (6.7.7) lib/active_fedora/predicates.rb:95:in `find_predicate'
active-fedora (6.7.7) lib/active_fedora/predicates.rb:38:in `find_graph_predicate'
active-fedora (6.7.7) lib/active_fedora/relationship_graph.rb:99:in `uri_predicate'
active-fedora (6.7.7) lib/active_fedora/relationship_graph.rb:17:in `add'
active-fedora (6.7.7) lib/active_fedora/semantic_node.rb:29:in `add_relationship'
active-fedora (6.7.7) lib/active_fedora/associations/has_and_belongs_to_many_association.rb:38:in `insert_record'
active-fedora (6.7.7) lib/active_fedora/associations/association_collection.rb:77:in `block (2 levels) in <<'
active-fedora (6.7.7) lib/active_fedora/associations/association_collection.rb:170:in `add_record_to_target_with_callbacks'
active-fedora (6.7.7) lib/active_fedora/associations/association_collection.rb:76:in `block in <<'
active-fedora (6.7.7) lib/active_fedora/associations/association_collection.rb:74:in `each'
active-fedora (6.7.7) lib/active_fedora/associations/association_collection.rb:74:in `<<'
/Users/matt/.rvm/gems/ruby-1.9.3-p429/bundler/gems/curate-01fa5853cab3/app/controllers/curation_concern/generic_works_controller.rb:34:in `setup_form'
/Users/matt/.rvm/gems/ruby-1.9.3-p429/bundler/gems/curate-01fa5853cab3/app/controllers/curation_concern/generic_works_controller.rb:6:in `new'
actionpack (4.0.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.0.4) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.0.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.0.4) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (4.0.4) lib/active_support/callbacks.rb:503:in `_run__959510420563521427__process_action__callbacks'
activesupport (4.0.4) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.4) lib/abstract_controller/callbacks.rb:17:in `process_action'
```

**Comment by flyingzumwalt** [comment]
You can grab the generated app from [https://github.com/curationexperts/absolute](https://github.com/curationexperts/absolute)
